### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by colindaven** [t-ogasawara/sam-to-bam#1]
Hi,

thanks for the nice tool. I had a few issues installing, thought I'd share them here.

Ubuntu 14.04 system

get build.sh from link

replace git: with https: so downloads will work

build fails with /usr/bin/ld: cannot find -ltcmalloc_minimal

sudo apt-get install libtcmalloc-minimal4

add in my case /usr/lib/ to global LD path

manually link library

sudo ln -s /usr/lib/libtcmalloc_minimal.so.4 /usr/lib/libtcmalloc_minimal.so

Seems to have worked, exe created

~/NAS01/programs/sam2bam$ build/samtools/samtools

libs - check
find /usr/ -name "*tcmalloc_mi*"

/usr/lib/libtcmalloc_minimal_debug.so.4

/usr/lib/libtcmalloc_minimal.so.4.1.2

/usr/lib/libtcmalloc_minimal.so.4

/usr/lib/libtcmalloc_minimal.so

/usr/lib/libtcmalloc_minimal_debug.so.4.1.2

**Comment by t-ogasawara** [comment]
@colindaven thank you for your interest in our tool. I replaced git: with https: so that build.sh works on sites where git: is not available. Thank you for your reporting the issue.

As for tcmalloc, you may want to use libgoogle-perftools-dev package instead of manually creating a symbolic. 

$ dpkg -L libgoogle-perftools-dev | grep libtcmalloc_minimal.so
/usr/lib/libtcmalloc_minimal.so
